core/urls.py
from django.urls import path,re_path
from . import views
app_name = 'core'
urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    path('contato/', views.contact, name='contact'),

]

courses/urls.py
from django.urls import path, re_path
from django.urls.conf import include

from . import views

app_name = 'courses'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^(?P<slug>[\w_-]+)/$',views.details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/inscrição/$',views.enrollment, name='enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/cancelar-inscrição/$',views.undo_enrollment, name='undo_enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/$',views.announcements, name='announcements'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$',views.show_announcements, name='show_announcement'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/$',views.lessons, name='lessons'),
    re_path(r'^(?P<slug>[\w_-]+)/aula/(?P<pk>\d+)/$',views.lesson, name='lesson'),
    re_path(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$',views.material, name='material'),
    #path('<slug:slug>/', CourseDetailSlugView.as_view()),
    #url('^(?P<slug>[\w_-]+)$', details, name='details'),
    #path('^(?P<slug>[\w_-]+)/$', details, name='details'),

   

]

curso/urls.py
from django.contrib import admin 
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import re_path


urlpatterns = [
    re_path(r'^', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('cursos/', include('courses.urls', namespace='courses')),
    path('forum/', include('forum.urls', namespace='forum')),
        

] 

if settings.DEBUG:  # Use local only
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # For serving media files

courses/models.py
from django import template
from django.db import models
from enum import unique
from django.conf import settings
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.signals import post_save
from django.template.defaultfilters import title
from core.mail import send_mail_template
from django.utils import timezone

class CourseManage(models.Manager):
    
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(description_icontains=query)
        )


class Course(models.Model):
    
    name = models.CharField(verbose_name='Nome', max_length=100)
    slug = models.SlugField('Atalho', unique=True)
    description = models.TextField('Descrição Simples', blank=True)
    about = models.TextField('Sobre o Curso', blank=True)
    start_date = models.DateField(
        'Data de Início', null= True, blank=True
        )

    image = models.ImageField(
        upload_to='images', verbose_name='Imagem', null=True, blank=True
    )

    create_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CourseManage()

    def __str__(self) :
        return self.name


    def get_absolute_url(self):
        return self.slug
    
    def release_lessons(self):
        today = timezone.now().date()
        return self.lessons.filter(release_date__gte=today)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']


class Lesson(models.Model):

    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    number = models.IntegerField('Número (ordem)', blank=True, default=0)
    release_date = models.DateField('Data de Liveração', blank=True, null=True)

    course = models.ForeignKey(
        Course,
        verbose_name='Curso',
        related_name='lessons',
        on_delete=models.CASCADE
    ) 
    
    created_at = models.DateTimeField('Criado em',auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self) :
        return self.name

    def is_available(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date >= today
        return False


    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['number']

class Material(models.Model):

    name = models.CharField('Nome', max_length=100)
    embedded = models.TextField('Vídeo embedded', blank=True)
    flie = models.FileField(upload_to='lessons/materials', blank=True, null=True)

    lesson = models.ForeignKey(
        Lesson,
        verbose_name='Aula',
        related_name='materials',
        on_delete=models.CASCADE
    )

    def is_embedded(self):
        return bool(self.embedded)

    def __str__(self) :
        return self.name

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiais'


class Enrollment(models.Model):

    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Cancelado'),
    )
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        on_delete=models.CASCADE,
        related_name='enrollments'
    )
    course = models.ForeignKey(
        Course, verbose_name='Curso', 
        on_delete=models.CASCADE, 
        related_name='enrollments'
    )
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=1, blank=True
        )
    
    created_at = models.DateTimeField('Criado em',auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    
    def active(self):
        self.status = 1
        self.save()

    def is_approved(self):
        return self.status == 1

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user', 'course'))

class Announcement(models.Model):
    course = models.ForeignKey(
        Course,
        related_name='announcements',
        verbose_name='Curso',
        on_delete=models.CASCADE,
    )
    title = models.CharField('Título', max_length=100)
    content = models.TextField('Conteúdo')

    created_at = models.DateTimeField('Criado em',auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    
    def __str__(self) :
        return self.title

    class Meta:
        verbose_name = 'Anúncio'
        verbose_name_plural = 'Anúncios'
        ordering = ['-created_at']
    
class Comment(models.Model):
    announcement = models.ForeignKey(
        Announcement,
        verbose_name = 'Comentário',
        related_name='comments',
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='usuário',
        on_delete=models.CASCADE
    )
    comment = models.TextField('Comentário', max_length=500)

    created_at = models.DateTimeField('Criado em',auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    
    class Meta:
        verbose_name ='Comentário'
        verbose_name_plural ='Comentários'
        ordering = ['created_at']

def post_save_announcement(instance, created, **kwargs):
    if created:
        subject = instance.title
        context = {
            'announcement': instance
        }
        template_name = 'announcement_mail.html'
        enrollments = Enrollment.objects.filter(
            course=instance.course, status=1
        )
        recipient_list = []
        for enrollment in enrollments:
            recipient_list = [enrollment.user.email]
        send_mail_template(subject, template_name, context, recipient_list)
        

models.signals.post_save.connect(
    post_save_announcement, sender=Announcement, dispatch_uid='post_save_announcement'
)

courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from core.mail import send_mail_template
from .models import Comment



class ContactCourse(forms.Form):
    
    name = forms.CharField(label='None', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )
    
    def send_email(self, course):
        subject = '[%s]Contato' % course
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message']
        }
        template_name = 'contact_email.html'
        send_mail_template(
            subject, template_name, context,
             [settings.CONTACT_EMAIL]
        )

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']

courses/views.py
from django import forms
from django.db.models.query import ValuesIterable
from django.shortcuts import redirect, render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template.defaultfilters import escapejs_filter
from .models import Course, Enrollment, Announcement, Lesson, Material
from  .forms import ContactCourse, CommentForm
from .decorators import enrollment_required

#from django.views.generic import DetailView


def index(request):
    courses = Course.objects.all()
    template_name = 'index.html'
    context = {
        'courses': courses
    }
    return render(request, template_name, context)
    

def details(request, slug):
    course = get_object_or_404(Course, slug=slug)
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_email(course)
            form = ContactCourse()
            
    else:
        form = ContactCourse()
    context['form'] = form
    context['course'] = course
    template_name = 'details.html'
    return render(request, template_name, context)

@login_required
def enrollment(request,slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, course=course
    )
    if created:
        #enrollment.active()
        messages.success(request, 'Você foi inscrito no curso com sucesso')
    else:
        messages.info(request, 'Você já está inscrito no curso')


    return redirect('accounts:dashboard')


@login_required
def undo_enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(
            Enrollment, user=request.user, course=course
        )
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso')
        return redirect('accounts:dashboard')
    template_name = 'undo_enrollment.html'
    context = {
        'enrollment': enrollment,
        'course': course
    }
    return render(request, template_name, context)

@login_required
@enrollment_required
def announcements(request,slug):
    course = request.course
    template_name = 'announcements.html'
    context = {
        'course': course,
        'announcements': course.announcements.all()
    }
    return render(request, template_name, context )

@login_required
@enrollment_required
def show_announcements(request, slug, pk):
    course = request.course
    announcement = get_object_or_404(course.announcements.all(), pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save()
        form = CommentForm()
        messages.success(request, 'Comentário salvo!')
    template_name = 'show_announcement.html'
    context = {
        'course': course,
        'announcement': announcement,
        'form': form     
    }
    return render(request, template_name, context)

@login_required
@enrollment_required
def lessons(request, slug):
    course = request.course
    template_name = 'lessons.html'
    lessons = course.release_lessons()
    if request.user.is_staff:
        lessons =  course.lessons.all()
    context = {
        'course': course,
        'lessons': lessons
    }
    return render(request, template_name, context)

@login_required
@enrollment_required
def lesson(request, slug, pk):
    course = request.course
    lesson = get_object_or_404(Lesson, pk=pk, course=course)
    if request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta aula não está disponível')
        return redirect('courses:lessons', slug=course.slug)
    template_name = 'lesson.html'
    context = {
        'course': course,
        'lesson': lesson
    }
    return render(request, template_name, context)

@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    material = get_object_or_404(Material, pk=pk, lesson__course=course)
    lesson = material.lesson
    if request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta material não está disponível')
        return redirect('courses:lessons', slug=course.slug, pk=lesson )
    if not material.is_embedded():
        return redirect(material.flie.url)
    template_name = 'material.html'
    context = {
        'course': course,
        'lesson': lesson,
        'material': material,
    }
    return render(request, template_name, context)

courses/templates/announcement_mail.html
{{ announcement.content|linebreaks }}

courses/templates/announcements.html
{% extends "course_dashboard.html" %}

{% block dashboard_content %}
{% for announcement in announcements %}
<div class="well">
    <h2>
        <a class="titles" href="{% url 'courses:show_announcement' course.slug announcement.pk %}">{{ announcement.title }}</a>
    </h2>
    <div class="titles">
    {{ announcement.content|linebreaks }}
    </div>
    <p>
        <a class="titles" href="{% url 'courses:show_announcement' course.slug announcement.pk %}#comments">
        <i class="fa fa-comments-o"></i>
        {% with comments_count=announcement.comments.count %}
        {{ comments_count }}
        Comentário{{ comments_count|pluralize }}
        {% endwith %}
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>Nenhum anúncio criado</h2>
</div>
{% endfor %}
{% endblock %}

courses/templates/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

courses/templates/course_dashboard.html
{% extends "dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
 <a  class="titles "href="{% url 'courses:announcements' course.slug %}">{{ course }}</a>
{% endblock %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="{% url 'courses:lessons' course.slug %}">
        <i class="fa fa-video-camera"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="{% url 'courses:announcements' course.slug %}">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="{% url 'forum:index' %}">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

courses/templates/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4 class="titles">Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button button-secondary">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3 class="titles">Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="button-enviar-datails">
                    <button type="submit" class=" pure-button button-secondary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

courses/templates/index.html
<br></br>
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h3 class="content-subhead">Listagem de Cursos do SimpleMOOC</h3>
            <p><strong>Abaixo a lista de cursos disponíveis na plataforma:</strong></p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">

            <a href="{{ course.get_absolute_url }}">
            
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

courses/templates/lesson.html
{% extends "course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    
    <a class="titles" href="{% url 'courses:lessons' course.slug %}">Aulas</a>
    
    <a class="titles" href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a>
{% endblock %}

{% block dashboard_content %}
<div class="well" >
    <h2><a class="titles" href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <div class="titles">
        {{ lesson.description|linebreaks }}
    </div>
    <p>
        <h4 class="titles">Material da Aula:</h4>
        <table class=" pure-table stretch">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                        {{ material }}
                    </td>
                    <td>
                        {% if material.is_embedded %}
                        <a href="{% url 'courses:material' course.slug material.pk %}">
                            <i class="fa fa-video-camera"></i>
                            Acessar
                        </a>
                        {% else %}
                        <a target="_blank" href="{{ material.file.url }}">
                            <i class="fa fa-download"></i>
                            Baixar
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

courses/templates/lessons.html
{% extends "course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
   <a class="titles" href="{% url 'courses:lessons' course.slug %}">Aulas</a>
{% endblock %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="well">
    <h2 class="titles"><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        <div class="titles">{{ lesson.description|truncatewords:'20' }}</div>
        <br />
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}" title="">
        <i class=" titles fa fa-eye"></i>
        Acessar Aula
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>
        Nenhuma aula disponível.
    </h2>
</div>
{% endfor %}
{% endblock %}

courses/templates/material.html
{% extends "course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <a class="titles" href="{% url 'courses:lessons' course.slug %}">Aulas</a>
    
    <a class="titles" href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a>
    
    <a class="titles" href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a class="titles" href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></h2>
    {{ material.embedded|safe }}
    <p>
        <a class="titles" href="{% url 'courses:lesson' course.slug lesson.pk %}">Voltar</a>
    </p>
</div>
{% endblock %}

courses/templates/show_announcement.html
{% extends "course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    
   <a class="titles" href="{% url 'courses:show_announcement' course.slug announcement.pk %}"> {{ announcement }}</a>
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2  class="titles">{{ announcement.title }}</h2>
        <div class="titles"> {{ announcement.content|linebreaks }}</div>
    </div>
    <div class="well">
        <h4 class="comments" id="comments">Comentários:
        <a class="fright" href="#add_comment">Comentar</a></h4>
        <hr>
        {% for comment in announcement.comments.all %}
        <div class="titles">
        <p>
            <strong>{{ comment.user }}:</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
        </div>
        </hr>
        {% empty %}
        <p>
            Nenhum comentário para este anúncio.
        </p>
        {% endfor %}
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="button-secondary pure-button">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

courses/templates/undo_enrollment.html
{% extends 'course_dashboard.html' %}

{% block dashboard_content %}
<form action=""  class="pure-form pure-form-aligned " method="post">
    {% csrf_token %}
    <h3 class="titles" style="text-align:center;">Você deseja realmente cancelar a inscrição deste curso?</h3>
    <div style="text-align:center;" class="pure-controls">
        <button type="submit" class="button-secondary pure-button">Confirmar</button>
        <a class="pure-button"href="{% url 'courses:announcements' course.slug %}" >Voltar</a>
        
    </div>
</form>
{% endblock %}