accounts/urls.py
from re import template
from django.conf.urls import url
from django.urls.conf import include, path, re_path
from django.views.generic import TemplateView
from . import views
from django.contrib.auth import views as auth

#from django.conf.urls import url

app_name = 'accounts'
urlpatterns = [
    re_path(r'^entrar/$', auth.LoginView.as_view(template_name='registration/login.html'), name='login'), 
    re_path(r'^sair/$', auth.LogoutView.as_view(), name='logout'),
    re_path(r'^$',views.dashboard, name='dashboard'),
    re_path(r'^cadastre-se/$',views.register, name='register'),
    re_path(r'^nova-senha/$',views.password_reset, name='password_reset'),
    re_path(r'^confirmar-nova-senha/(?P<key>\w+)/$',views.password_reset_confirm, name='password_reset_confirm'),
    re_path(r'^editar/$',views.edit, name='edit'),
    re_path(r'^editar-senha/$',views.edit_password, name='edit_password'),
        

    #re_path(r'^sair/$',views.logout_view, name='logout'),
    #path('cadastre-se', TemplateView.as_view(template_name="register.html"),name='register'),
    #path(r'^cadastre-se/$', 'curso.accounts.views.register', name='register'),
    #path('cadastre-se', include('django.contrib.auth.urls.register')),
   
   

]

core/urls.py
from django.urls import path,re_path
from . import views
app_name = 'core'
urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    path('contato/', views.contact, name='contact'),

]

courses/urls.py
from django.urls import path, re_path
from django.urls.conf import include

from . import views

app_name = 'courses'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^(?P<slug>[\w_-]+)/$',views.details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/inscrição/$',views.enrollment, name='enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/cancelar-inscrição/$',views.undo_enrollment, name='undo_enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/$',views.announcements, name='announcements'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$',views.show_announcements, name='show_announcement'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/$',views.lessons, name='lessons'),
    re_path(r'^(?P<slug>[\w_-]+)/aula/(?P<pk>\d+)/$',views.lesson, name='lesson'),
    re_path(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$',views.material, name='material'),
    #path('<slug:slug>/', CourseDetailSlugView.as_view()),
    #url('^(?P<slug>[\w_-]+)$', details, name='details'),
    #path('^(?P<slug>[\w_-]+)/$', details, name='details'),

   

]

curso/urls.py
from django.contrib import admin 
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import re_path


urlpatterns = [
    re_path(r'^', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('cursos/', include('courses.urls', namespace='courses')),
    path('forum/', include('forum.urls', namespace='forum')),
        

] 

if settings.DEBUG:  # Use local only
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # For serving media files

accounts/models.py
from django.db import models

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
    UserManager)
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome de Usuário', max_length=30, unique=True, 
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
            'O nome de usuário só pode conter letras, digitos ou os '
            'seguintes caracteres: @/./+/-/_', 'invalid')]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):

    user = models.ForeignKey(
        
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        on_delete=models.CASCADE,
        related_name='resets'
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Data em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']

accounts/forms.py
from accounts.models import PasswordReset
from core.utils import generate_hash_key
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import fields
from core.mail import send_mail_template

User = get_user_model()


class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError('Nenhum usuário encontrado com este endereço de e-mail')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'password_reset_mail.html'
        subject = 'Criar nova senha no Simple MOOC'
        context = {'reset': reset,}
        send_mail_template(subject, template_name, context, [user.email])

class RegisterForm(forms.ModelForm):
    
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1!= password2:
            raise forms.ValidationError('A confirmação de senha não está correta' )
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
        
    class Meta:
        model = User
        fields = ['username', 'email']


class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

accounts/views.py
from re import template
from django.contrib.auth import forms
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import (UserCreationForm, PasswordChangeForm, SetPasswordForm)
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
#from django.contrib.auth import logout

from core.utils import generate_hash_key
from courses.models import Enrollment

from .forms import RegisterForm, EditAccountForm, PasswordResetForm, User
from .models import PasswordReset

User = get_user_model()

@login_required
def dashboard(request):
    template_name = 'dashboard.html'
    context = {}
    return render(request, template_name, context)



def register(request):
    template_name = 'register.html'
    try:
        logout(request)
    except:
        pass
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        user = authenticate(username=user.username, password=form.cleaned_data['password1'])
        login(request, user)
        return redirect('core:home')
    context = {
      'form': form
    }
    return render(request, template_name, context)


def password_reset(request):
    template_name = 'password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


def password_reset_confirm(request, key):
    print("s")
    template_name = 'password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit(request):
    template_name = 'edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Os dados da sua conta foram alterados com sucesso')
            return redirect('accounts:dashboard')
           
    else:
        form = EditAccountForm(instance=request.user)
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)



#def logout_view(request):
#    template_name = 'home.html'
#    logout(request)
#   return render ( request, template_name )

accounts/templates/dashboard.html
{% extends "base.html" %}
{% load courses_tags %}
{% block content %}
{% load_my_courses user as enrollments %}

<br>
<div class="pure-g-r content-ribbon ">
    <div class="pure-u-1">
        <h4>
            {% block breadcrumb %}
            <a class="titles" href="{% url 'accounts:dashboard' %}"> Meu Painel </a>
            {% endblock %}
        </h4>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open new_class">
            <ul>
                <li class="pure-menu-heading">
                    Bem-Vindo, {{ user }}
                </li>

                {% block menu_options %}
                <li class="pure-menu-heading">Cursos</li>
                {% for enrollment in enrollments %}
                <li>
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}">
                        <i class="fa fa-book"></i>
                        {{ enrollment.course }}
                    </a>
                </li>
                {% empty%}
                <li>Nenhum curso matriculado</li>
                {% endfor %}
                <li class="pure-menu-heading"> Configuração Conta</li>
                <li>
                    <a href="{% url 'accounts:edit' %}">
                        <i class="fa fa-cog"></i>
                        Editar Informações
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:edit_password' %}">
                        <i class="fa fa-lock"></i>
                        Editar Senha
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <h2 class="my_cursos_menu_dashboard">Meus Cursos</h2>
            {% for enrollment in enrollments %}
            <div class="well ">
                <h3 class="titles">{{ enrollment.course }}
                ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data' }})
                </h3>
                <div class="titles">
                    {{ enrollment.course.description|linebreaks }}
                </div>               
                <div class="pure-controls">
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="button-secondary pure-button">Acessar</a>
                    <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="button-error pure-button">Cancelar</a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1">
                <p>Nenhum curso inscrito</p>
            </aside>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>
<br>
{% endblock %}

accounts/templates/edit.html
{% extends 'dashboard.html' %}
{% block breadcrumb %}
    {{ block.super }}
    
   <a class="titles" href="{% url 'accounts:edit' %}">Editar Conta</a>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-aligned " method="post">
    {% csrf_token %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">    
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="button-login">
            <button type="submit" class="pure-button button-secondary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

accounts/templates/edit_password.html
{% extends "dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
  
  <a class="titles" href="{% url 'accounts:edit_password' %}">Editar Senha</a>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-aligned " method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="button-login">
            <button type="submit" class="pure-button button-secondary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

accounts/templates/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Um e-mail foi enviando para você com mais detalhes de como criar uma nova senha</p>
        {% else %}
        <h2 class="titles">Informe seu E-mail</h2>
        <form class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="button-login">
                    <button type="submit" class="pure-button button-secondary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criada com sucesso</p>
        {% else %}
        <h2 class="titles">Informe sua nova Senha</h2>
        <form class="pure-form  pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="button-login">
                    <button type="submit" class="pure-button button-secondary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

accounts/templates/password_reset_mail.html
<p>Para criar uma nova senha, acesse o link:
     <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para Criar Nova Senha">Criar Nova Senha</a>
    
</p>

accounts/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2 class="titles">Informe seus dados</h2>
        <form class="pure-form  pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="button-login">
                    <button type="submit" class="pure-button button-secondary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}