accounts/urls.py
from re import template
from django.conf.urls import url
from django.urls.conf import include, path, re_path
from django.views.generic import TemplateView
from . import views
from django.contrib.auth import views as auth

#from django.conf.urls import url

app_name = 'accounts'
urlpatterns = [
    re_path(r'^entrar/$', auth.LoginView.as_view(template_name='registration/login.html'), name='login'), 
    re_path(r'^sair/$', auth.LogoutView.as_view(), name='logout'),
    re_path(r'^$',views.dashboard, name='dashboard'),
    re_path(r'^cadastre-se/$',views.register, name='register'),
    re_path(r'^nova-senha/$',views.password_reset, name='password_reset'),
    re_path(r'^confirmar-nova-senha/(?P<key>\w+)/$',views.password_reset_confirm, name='password_reset_confirm'),
    re_path(r'^editar/$',views.edit, name='edit'),
    re_path(r'^editar-senha/$',views.edit_password, name='edit_password'),
        

    #re_path(r'^sair/$',views.logout_view, name='logout'),
    #path('cadastre-se', TemplateView.as_view(template_name="register.html"),name='register'),
    #path(r'^cadastre-se/$', 'curso.accounts.views.register', name='register'),
    #path('cadastre-se', include('django.contrib.auth.urls.register')),
   
   

]

core/urls.py
from django.urls import path,re_path
from . import views
app_name = 'core'
urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    path('contato/', views.contact, name='contact'),

]

curso/urls.py
from django.contrib import admin 
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import re_path


urlpatterns = [
    re_path(r'^', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('cursos/', include('courses.urls', namespace='courses')),
    path('forum/', include('forum.urls', namespace='forum')),
        

] 

if settings.DEBUG:  # Use local only
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # For serving media files

forum/urls.py
from courses import urls
from django.urls import path,re_path
from . import views
from django.views.generic import TemplateView

import forum



app_name = 'forum'
urlpatterns = [
     re_path(r'^$', views.index, name='index'),
     re_path(r'^tag/(?P<tag>[\w_-]+)/$', views.index, name='index_tagged'),
     #re_path(r'^$',TemplateView.as_view(template_name="forum/index.html"),name='index'),
     #re_path(r'^tag/(?P<tag>[\w_-]+)/$',TemplateView.as_view(template_name="forum/index.html"),name='index_tagged'),
     re_path(r'^respostas/(?P<pk>\d+)/correta/$',views.reply_correct,name='reply_correct'),
     re_path(r'^respostas/(?P<pk>\d+)/incorreta/$',views.reply_incorrect,name='reply_incorrect'),
     re_path(r'^(?P<slug>[\w_-]+)/$', views.thread,name='thread'),
     #re_path(r'^(?P<slug>[\w_-]+)/$',TemplateView.as_view(template_name="forum/thread.html"),name='thread'),

     #path(r'^$',index,name='index'),
     #re_path(r'^tag/(?P<tag>[\w_-]+)/$',views.index, name='index_tagged'),
]

core/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render (request, 'home.html',)

def contact(request):
    return render(request, 'contact.html')

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'forum:index' %}">Fórum</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
            <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% block scripts %}{% endblock %}
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% block content %}

<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="#">Fórum</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
            <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1 class="titles">Fale conosco</h1>
            <h5 class="titles">Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</h5>
            <h4 class="comments">Links:</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
                <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
            </ul>
        </div>
    </div>
   
{% endblock %}

core/templates/home.html
{% extends 'base.html' %}
{% block content %}


    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h2 class="splash-subhead">
                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
  